# ==================================
# DB (Database)
# ==================================
# (Using KH Academy's public DB server)
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=soso
spring.datasource.password=soso

# ==================================
# DBCP (Database Connection Pool)
# ==================================
spring.datasource.dbcp2.max-total=20
spring.datasource.dbcp2.min-idle=5

# ==================================
# Multipart (File Upload)
# ==================================
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# ==================================
# API Keys
# ==================================
# (Kakao REST API Key for RegionDataInitializer)
kakao.api.key=a68ebd8838af82255ef7a650b0998a3e

