spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=soso
spring.datasource.password=soso

# ===============================================
# 2. Connection Pool
# ===============================================
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5

# multipart
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB 
spring.servlet.multipart.max-request-size=10MB

# springdoc
springdoc.api-docs.enabled=true
springdoc.packages-to-scan=com.project.soso.restcontroller
springdoc.swagger-ui.path=/api.html

#mybatis
mybatis.type-aliases-package=com.project.soso.dto, com.project.soso.vo
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.mapper-locations=classpath:mybatis/**/*-mapper.xml
mybatis.configuration.jdbc-type-for-null=NULL

#logging
logging.level.root=WARN
logging.level.com.project.soso=DEBUG
logging.level.com.project.soso.mapper=TRACE

#custom properties
custom.email.username=thk0411
custom.email.password=5XXM45PG2SDV